### DISCUSSION TITLE
Why use 'or' for 'set registry value' instead of 'and'?

### DISCUSSION THREAD

**Discussion by jorik-utwente** [fireeye/capa-rules#899] [Q&A] [answered]
Many persistence rules that involve writing to the registry use a pattern similar to:
```
- and:
  - or:
    - match: set registry value
    - number: 0x80000001 = HKEY_CURRENT_USER
    - number: 0x80000002 = HKEY_LOCAL_MACHINE
 ...
```
Does this not result in false positives when reading registry values?

I would expect the pattern to look like this:
```
- and:
  - match: set registry value
  - or:
    - number: 0x80000001 = HKEY_CURRENT_USER
    - number: 0x80000002 = HKEY_LOCAL_MACHINE
 ...
```

Example here: https://github.com/mandiant/capa-rules/blob/master/persistence/registry/run/persist-via-run-registry-key.yml
To my understanding, reading the registry key from e.g. `Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows\\load` will result in a false positive. Or am I missing something?

Thanks!
