### ISSUE TITLE
Identify Rust binaries

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa-rules#125]
For https://github.com/fireeye/capa-rules/pull/124 @re-fox provided a Rust binary.

Let's gather robust ways to identify such binaries using capa.

**Comment by mike-hunhoff** [comment]
We should also do this for Go binaries.

**Comment by 0x262D** [comment]
Some strings from a simple hello world binary compiled with rustc (x64 if that matters) I located with grep -E 'rust|\.rs'
The Program: 
`fn main() {
    println!("Hello, world!");
}`

rust_panic
src\libcore\fmt\mod.rs
src\libcore\slice\memchr.rs
src\libcore\str\mod.rs
src\libcore\unicode\printable.rs
src\libcore\unicode\unicode_data.rs
src\libcore\num\mod.rs
. . . 
An interesting substring I found in multiple strings was **04488afe34512aa4c33566eb16d8c912a3ae04f9** which has a little over 100 hits on google which seems to just be Rust projects.

**Comment by re-fox** [comment]
I was looking into this as well.  

I tested some Windows/Linux 32&64 with and without stripping.  The `rust_panic` string is a function symbol and won't appear in stripped executables.

The hash that you're seeing `04488afe34512aa4c33566eb16d8c912a3ae04f9` is (I believe) a commit hash, which rust will include in the compiled build paths.  This is likely to change across builds and samples.

I've had some testing luck with looking into the named pipe that's in the std Windows libs.  (Source -> https://docs.input.fun/rust/1.39.0/src/std/sys/windows/pipe.rs.html). The issue here is that if no function is using it you'll see code artifacts ( `CreateNamedPipeW` in the imports), but no references to code.  So CAPA likely won't see it either.

I have a rule that is working looking for the string that's in the Rust panicking function -> https://github.com/rust-lang/rust/blob/master/library/std/src/panicking.rs .  This rule currently is just looking for 2 strings though, and I was hoping to tighten it down a bit.

```yaml
rule:
  meta:
    name: compiled with rust
    namespace: compiler/rust
    author: "@_re_fox"
    scope: function
    examples:
      - c3341b7dfbb9d43bca8c812e07b4299f:0x45F490
  features:
    - and:
      - basic block:
        - string: /run with \`RUST_BACKTRACE=1\` environment variable/
      - basic block:
        - string: /thread '' panicked at '',/
```
