### ISSUE TITLE
[Question] Instruction-level scope?

### ISSUE THREAD

**Issue by recvfrom** [fireeye/capa-rules#131]
From re-reading the documentation, is it true that the following are equivalent:
```
      - and:
        - number: 7
        - mnemonic: rol
      - and:
        - number: 0x54655307
        - mnemonic: imul
```
and:
```
      - mnemonic: imul
      - mnemonic: rol
      - number: 7
      - number: 0x54655307
```
If so, is there a way to make it so that the mnemonic and number from each `and` clause in the first example must occur in the same instruction?  For instance, is there a way to specify instruction-level scope for that block?

**Comment by williballenthin** [comment]
it is true that the two examples are equivalent. we often use nesting like this to logically group related things, even if the end result is the same.

there is not an instruction scope. the smallest scope that capa supports is basic block scope. i think in early versions we may have experimented with an instruction-level scope, but didn't find a common use for it. this is something that we could add in if there are some compelling reasons to do so.

**Comment by recvfrom** [comment]
Got it - thanks for the info.

I was looking at creating a rule to detect HC-128 usage, but there aren't any unique crypto constants that it uses... The following could work, but I worry that it might be FP prone if the numbers are decoupled from the instruction mnemonics.  What are your thoughts?
```
    - and:
      - and:
        - number: 0x110
        - mnemonic: cmp
      - and:
        - number: 0x0F
        - mnemonic: shl
      - and:
        - number: 0x11
        - mnemonic: shr
      - and:
        - number: 0xD
        - mnemonic: shl
      - and:
        - number: 0x13
        - mnemonic: shr
      - and:
        - number: 0xA
        - mnemonic: shr
      - and:
        - number: 0x19
        - mnemonic: shl
      - and:
        - number: 0x7
        - mnemonic: shr
      - and:
        - number: 0xE
        - mnemonic: shl
      - and:
        - number: 0x12
        - mnemonic: shr
      - and:
        - number: 0x3
        - mnemonic: shr
      - mnemonic: or
      - characteristic: nzxor
```
