### ISSUE TITLE
syscall-using-heavens-gate

### ISSUE THREAD

**Issue by recvfrom** [fireeye/capa-rules#160]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your rule idea isn't already filed: [search](https://github.com/fireeye/capa-rules/issues?q=is%3Aissue+is%3Aopen+)

## Summary

Would it make sense to write a rule that looks for a function that syscall's and leverages the heaven's gate technique?

## Examples

From: https://download.bitdefender.com/resources/files/News/CaseStudies/study/318/Bitdefender-TRR-Whitepaper-Maze-creat4351-en-EN-GenericUse.pdf

![image](https://user-images.githubusercontent.com/36489577/97061802-3251c800-1566-11eb-8f83-1c7163d3a632.png)

Sample: https://www.virustotal.com/gui/file/953d574ef0f49e886e270c2887586aab5c0d37616dd99f422838a1257abdbe3b/community

## Features

Maybe the following with function scope:
```
push 0x33
retf
syscall
```
and/or
```
syscall
move 0x23
retf
```

## Additional context

N/A

### Namespace

Not sure...

### References

N/A

### Other rule meta information

N/A

**Comment by williballenthin** [comment]
yeah I think this is a neat idea! the technique isn't super common, but when it's there, I'd love capa to explain what's going on (I certainly forget about 0x23 and 0x33). 

looks like you have a first draft of the rule, want to open a PR and we can test it a bit further?

**Comment by recvfrom** [comment]
I initially came up with the following:
```
    - and:
      - or:
        - and:
          - number: 0x33 = CS=0x33 indicating 64-bit mode
          - or:
            - mnemonic: push
            - mnemonic: mov
        - and:
          - number: 0x23 = CS=0x23 indicating 32-bit mode
          - or:
            - mnemonic: push
            - mnemonic: mov
      - mnemonic: retf
      - mnemonic: syscall
```

but it looks like the 64-bit code doesn't get disassembled, so neither the syscall nor the code to return back to 32-bit mode get analyzed (my version of capa is be a bit outdated now, so I can try with the latest tomorrow):
```
...
insn: 0x10002394: number(0x33)
insn: 0x10002394: number/x32(0x33)
insn: 0x10002394: mnemonic(push)
insn: 0x10002396: mnemonic(call)
insn: 0x1000239b: characteristic(calls from)
bb  : 0x1000239b: basic block
insn: 0x1000239b: number(0x5)
insn: 0x1000239b: number/x32(0x5)
insn: 0x1000239b: mnemonic(add)
insn: 0x1000239f: mnemonic(retf)
func: 0x100012d0: characteristic(calls to)
bb  : 0x100023ee: basic block
insn: 0x100023ee: mnemonic(jmp)
insn: 0x100023ee: characteristic(cross section flow)
...
```

I think I might just omit the `syscall` check and set the scope to basic block. Does that seem sufficient?  `retf` should be pretty rare, I'd imagine.

Also, where should this rule exist?  Would `executable/pe` make sense? Or maybe under `anti-analysis` somewhere?

Thanks!

**Comment by recvfrom** [comment]
I forgot that the `call` would split the `push 0x33` and `retf` into separate basic blocks, so my idea above wouldn't work... I added a PR with another solution - let me know what you think. We could also look for the byte sequences associated with the 64-bit instructions instead of relying on the disassembly, if you think that adds value.

**Comment by williballenthin** [comment]
its a bummer that our disassembly frameworks won't handle the 32/64-bit code well, but im not sure that we can expect any fixes there soon.

like you, i presume that `retf` is a pretty uncommon instruction, but i'm not 100% sure. do you think its reasonable to constrain the function to only have less than 3 BB or something similar?

i think this should go under anti-analysis, maybe under anti-disasm or similar? i'm open to suggestions here.

**Comment by williballenthin** [comment]
> We could also look for the byte sequences associated with the 64-bit instructions instead of relying on the disassembly, if you think that adds value.

fyi: i dont think we have a feature that can do this right now (bytes matching only works for referenced global variables, not arbitrary parts of the program).

**Comment by williballenthin** [comment]
i bet its feasible to write a yara rule for this sequence of instructions, too. then it would be interesting to retrohunt VT and see what comes up...

**Comment by recvfrom** [comment]
I'm running with the following and already there are lots of results... Interesting!
```
rule HeavensGate
{
    meta:
        author = "Andrew Williams (@recvfrom) @ Cisco Talos"
        description = "Look for instructions associated with Heaven's Gate"
        date = "2020-10-27"
    strings:
        /*
         *  6A 33             push    33h ; '3'
         *  E8 00 00 00 00    call    $+5
         *  83 04 24 05       add     dword ptr [esp+0], 5
         *  CB                retf
         */
        $retf_to_64bit_mode = {6a33e80000000083042405cb}
        /*
         *  E8 00 00 00 00             call    $+5
         *  C7 44 24 04 23 00 00 00    mov     dword ptr [esp+4], 23h ; '#'
         *  83 04 24 0D                add     dword ptr [esp], 0Dh
         *  CB                         retf
         */
        $retf_to_32bit_mode = {e800000000c7442404230000008304240dcb}

    condition:
        (uint16(0) == 0x5A4D and uint32(uint32(0x3C)) == 0x00004550) and
        $retf_to_64bit_mode or $retf_to_32bit_mode
}
```

**Comment by recvfrom** [comment]
Looks like the majority of those samples from VT don't trigger the capa rule because the byte sequence appears in a PE appended to the end of the executable

Looking at a sample like 30ea910458e784546524001e683cd57374f05a77f57233c93b33adcf008de91b that does, it looks like the basic block constraint might miss some instances of the technique...
```
function @ 0x407245
  and:
    and:
      or:
        mnemonic: push = 'push 33h' @ 0x407245, 0x407251, 0x4072FA
        mnemonic: mov = cover any mov ESP / EBP equivalents @ 0x407246, 0x407248, 0x407256, 0x40725D, and 25 more...
      number: 0x33 = set up retf to push 0x33 to CS indicating 64-bit mode @ 0x4072FA
    mnemonic: call = 'call $+5' pushes the current EIP onto the stack, +5 to jump past call insn bytes @ 0x4072FC
    and:
      mnemonic: add = 'add dword ptr[esp], 5' updates the return address to point after retf @ 0x407278, 0x407299, 0x4072BA, 0x407301
      number: 0x5 = length of add + retf insn bytes @ 0x407301
    mnemonic: retf = set EIP = [ESP] and CS = [ESP+4] @ 0x407305
    count(basicblock): 100 or fewer @ 0x407245, 0x407256, 0x40726B, 0x407273, and 10 more...
function @ 0x407378
  and:
    and:
      or:
        mnemonic: push = 'push 33h' @ 0x407378, 0x407382, 0x407383, 0x4073A4
        mnemonic: mov = cover any mov ESP / EBP equivalents @ 0x407379, 0x407386, 0x407389, 0x40739A, and 3 more...
      number: 0x33 = set up retf to push 0x33 to CS indicating 64-bit mode @ 0x4073A4
    mnemonic: call = 'call $+5' pushes the current EIP onto the stack, +5 to jump past call insn bytes @ 0x4073A6
    and:
      mnemonic: add = 'add dword ptr[esp], 5' updates the return address to point after retf @ 0x4073AB
      number: 0x5 = length of add + retf insn bytes @ 0x4073AB
    mnemonic: retf = set EIP = [ESP] and CS = [ESP+4] @ 0x4073AF
    count(basicblock): 100 or fewer @ 0x407378, 0x407386, 0x407390, 0x407394, and 3 more...
function @ 0x4075D0
  and:
    and:
      or:
        mnemonic: push = 'push 33h' @ 0x4075D0, 0x4075D3, 0x4075D4, 0x4075D9, and 2 more...
        mnemonic: mov = cover any mov ESP / EBP equivalents @ 0x4075D1, 0x4075DD, 0x4075E0, 0x4075F1, and 2 more...
      number: 0x33 = set up retf to push 0x33 to CS indicating 64-bit mode @ 0x4075F7
    mnemonic: call = 'call $+5' pushes the current EIP onto the stack, +5 to jump past call insn bytes @ 0x4075F9
    and:
      mnemonic: add = 'add dword ptr[esp], 5' updates the return address to point after retf @ 0x4075FE
      number: 0x5 = length of add + retf insn bytes @ 0x4075FE
    mnemonic: retf = set EIP = [ESP] and CS = [ESP+4] @ 0x407602
    count(basicblock): 100 or fewer @ 0x4075D0, 0x4075DD, 0x4075E7, 0x4075EB, and 3 more...
function @ 0x40766E
  and:
    and:
      or:
        mnemonic: push = 'push 33h' @ 0x40766E, 0x407671, 0x407672, 0x40767B
        mnemonic: mov = cover any mov ESP / EBP equivalents @ 0x40766F
      number: 0x33 = set up retf to push 0x33 to CS indicating 64-bit mode @ 0x40767B
    mnemonic: call = 'call $+5' pushes the current EIP onto the stack, +5 to jump past call insn bytes @ 0x40767D
    and:
      mnemonic: add = 'add dword ptr[esp], 5' updates the return address to point after retf @ 0x407682
      number: 0x5 = length of add + retf insn bytes @ 0x407682
    mnemonic: retf = set EIP = [ESP] and CS = [ESP+4] @ 0x407686
    count(basicblock): 100 or fewer @ 0x40766E, 0x407682
```

The functionality making use of Heaven's Gate seems pretty generic, though... Maybe the technique is employed as anti-analysis?  Otherwise I can't think of why the CS change would be needed.
```
.text:004073A4                 push    33h ; '3'
.text:004073A6                 call    $+5
.text:004073AB                 add     [esp+1Ch+var_1C], 5
.text:004073AF                 retf
.text:004073B0 ; ---------------------------------------------------------------------------
.text:004073B0                 push    edi
.text:004073B1                 push    esi
.text:004073B2                 mov     edi, [ebp+8]
.text:004073B5                 dec     eax
.text:004073B6                 mov     esi, [ebp+var_C]
.text:004073B9                 mov     ecx, [ebp+arg_8]
.text:004073BC                 mov     eax, ecx
.text:004073BE                 and     eax, 3
.text:004073C1                 shr     ecx, 2
.text:004073C4                 repe cmpsd
.text:004073C6                 jnz     short loc_4073E1
.text:004073C8                 test    eax, eax
.text:004073CA                 jz      short loc_4073DD
.text:004073CC                 cmp     eax, 1
.text:004073CF                 jz      short loc_4073DA
.text:004073D1                 cmpsw
.text:004073D3                 jnz     short loc_4073E1
.text:004073D5                 cmp     eax, 2
.text:004073D8                 jz      short loc_4073DD
.text:004073DA
.text:004073DA loc_4073DA:                             ; CODE XREF: sub_407378+57↑j
.text:004073DA                 cmpsb
.text:004073DB                 jnz     short loc_4073E1
.text:004073DD
.text:004073DD loc_4073DD:                             ; CODE XREF: sub_407378+52↑j
.text:004073DD                                         ; sub_407378+60↑j
.text:004073DD                 mov     [ebp+var_1], 1
.text:004073E1
.text:004073E1 loc_4073E1:                             ; CODE XREF: sub_407378+4E↑j
.text:004073E1                                         ; sub_407378+5B↑j ...
.text:004073E1                 pop     esi
.text:004073E2                 pop     edi
.text:004073E3                 call    $+5
.text:004073E8                 mov     dword ptr [esp+4], 23h ; '#'
.text:004073F0                 add     [esp+var_s0], 0Dh
.text:004073F4                 retf
```

```
.text:004075F7                 push    33h ; '3'
.text:004075F9                 call    $+5
.text:004075FE                 add     [esp+18h+var_18], 5
.text:00407602                 retf
.text:00407603 ; ---------------------------------------------------------------------------
.text:00407603                 push    edi
.text:00407604                 push    esi
.text:00407605                 mov     edi, [ebp+8]
.text:00407608                 dec     eax
.text:00407609                 mov     esi, [ebp+var_8]
.text:0040760C                 mov     ecx, [ebp+arg_8]
.text:0040760F                 mov     eax, ecx
.text:00407611                 and     eax, 3
.text:00407614                 shr     ecx, 2
.text:00407617                 rep movsd
.text:00407619                 test    eax, eax
.text:0040761B                 jz      short loc_40762A
.text:0040761D                 cmp     eax, 1
.text:00407620                 jz      short loc_407629
.text:00407622                 movsw
.text:00407624                 cmp     eax, 2
.text:00407627                 jz      short loc_40762A
.text:00407629
.text:00407629 loc_407629:                             ; CODE XREF: sub_4075D0+50↑j
.text:00407629                 movsb
.text:0040762A
.text:0040762A loc_40762A:                             ; CODE XREF: sub_4075D0+4B↑j
.text:0040762A                                         ; sub_4075D0+57↑j
.text:0040762A                 pop     esi
.text:0040762B                 pop     edi
.text:0040762C                 call    $+5
.text:00407631                 mov     dword ptr [esp+4], 23h ; '#'
.text:00407639                 add     [esp+var_s0], 0Dh
.text:0040763D                 retf
```
