### ISSUE TITLE
enumerate-domain-trust-relationships

### ISSUE THREAD

**Issue by recvfrom** [fireeye/capa-rules#174]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your rule idea isn't already filed: [search](https://github.com/fireeye/capa-rules/issues?q=is%3Aissue+is%3Aopen+)

## Summary

We could write a rule that looks for an EXE importing `DsEnumerateDomainTrustsA` / `DsEnumerateDomainTrustsW` or maybe that has the strings `nltest` / `nltest.exe`) `/domain_trusts`).

## Examples

38a41e8128ae3955d541c8a00a93de1cd10a01c58368c8254a35659f8627ba30

```
.text:0040E33D                 push    eax             ; DomainCount
.text:0040E33E                 lea     eax, [ebp+Domains]
.text:0040E341                 push    eax             ; Domains
.text:0040E342                 push    dword_46D1DC[esi] ; Flags
.text:0040E348                 push    0               ; ServerName
.text:0040E34A                 call    ds:DsEnumerateDomainTrustsA
.text:0040E350                 cmp     eax, 6BAh
.text:0040E355                 jz      short loc_40E3AA
.text:0040E357                 xor     ebx, ebx
.text:0040E359                 cmp     [ebp+DomainCount], ebx
.text:0040E35C                 jbe     short loc_40E398
.text:0040E35E                 xor     edi, edi
```

## Features

See above

## Additional context

N/A

### Namespace

collection/network

### References

https://attack.mitre.org/techniques/T1482/
https://twitter.com/sixdub/status/1321979931098812416/photo/1

### Other rule meta information

T1482

**Comment by re-fox** [comment]
Providing another data point

I was recently looking at sample `3400a7df9ec3dc8283d5ac7accb6935691e93feda066cc46c6c04d67f7f87b2b` and it contains the following string which could also be used in the rule.

```
nltest.exe /domain_trusts /all_trusts
```

**Comment by johnk3r** [comment]
Hello,

I will write this rule.

**Comment by johnk3r** [comment]
Hey @mr-tz ,

after creating the rule, how does the validation and submission process work?

I didn't understand how to correctly fill in the examples. Would it be **md5: entrypoint**?

`
rule:
  meta:
    name: Detect Domain Trust Discovery 
    namespace: collection/network
    author: johnk3r
    scope: function
    att&ck:
      - Discovery::Domain Trust Discovery  [T1482]
    examples:
      - 0796f1c1ea0a142fc1eb7109a44c86cb:0x403CBD
      - 0731679c5f99e8ee65d8b29a3cabfc6b:0x402350
  features:
    - or:
      - api: DsEnumerateDomainTrusts
      - string: /nltest.exe/i
      - string: /domain/i
`

![domaintrust](https://user-images.githubusercontent.com/6247648/102695998-e344ae00-4209-11eb-9d78-c5f4836762f5.png)

**Comment by mr-tz** [comment]
It's `md5:function offset`, so from the match above `0796f1c1ea0a142fc1eb7109a44c86cb:0x40222F`. I'll open an issue to update the documentation. Thanks!

If you include sample references, please upload the files to https://github.com/fireeye/capa-testfiles so we can test the matches.

**Comment by johnk3r** [comment]
right,

Eu tentei fazer o upload mas tenho a seguinte mensagem:

```
Uploads are disabled.
File uploads require push access to this repository
```

Segue abaixo a regra atualizada:

```
rule:
  meta:
    name: Detect Domain Trust Discovery 
    namespace: collection/network
    author: johnk3r
    scope: function
    att&ck:
      - Discovery::Domain Trust Discovery  [T1482]
    examples:
      - 0796f1c1ea0a142fc1eb7109a44c86cb:0x40222F
      - 0731679c5f99e8ee65d8b29a3cabfc6b:0x40408E
  features:
    - or:
      - api: DsEnumerateDomainTrusts
      - string: /nltest.exe/i
```
