### ISSUE TITLE
execute anti-VM instructions

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa-rules#194]
## Summary

Due to missing library detection in the vivisect backend (see https://github.com/fireeye/capa/issues/74) `execute anti-VM instructions` often triggers on runtime functions such as `___isa_available_init`. The hit is "correct" but can be misleading.

## Possible improvements

Propose to remove cpuid from this rule for the time being.

Plus `reference processor manufacturer constants` has the optional mnemonic `cpuid` and the respective constants:

```yaml
  features:
    - and:
      - mnemonic: cmp
      - or:
        - number: 0x61774D56    # 'awMV' (VMware)
        - number: 0x566E6558    # 'VneX' (Xen HVM)
        - number: 0x7263694D    # 'rciM' (Microsoft Hyper-V)
        - number: 0x4B4D564B    # 'KMVK' (KVM)
        - number: 0x70726C20    # 'prl ' (Parallels)
        - number: 0x786F4256    # 'xoBV' (VirtualBox)
      - optional:
        - mnemonic: cpuid
```
