### ISSUE TITLE
BITS via COM

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa-rules#332]
```
  features:
    - and:
      - bytes: 0D 4C E3 5C C9 0D 1F 4C 89 7C DA A1 B7 8C EE 7C = IBackgroundCopyManager
      - bytes: 4B D3 91 49 A1 80 91 42 83 B6 33 28 36 6B 90 97 = BITS_ControlClass
      - bytes: 39 07 B5 54 6F 68 EB 45 9D FF D6 A9 A0 FA A9 AF = IBackgroundCopyJob2
```

EDIT: shortened bytes
