### ISSUE TITLE
Preventing with just one child under 'And' or 'Or' ?

### ISSUE THREAD

**Issue by ruppde** [fireeye/capa-rules#382]
Statements with just one child under 'And' or 'Or' don't make sense and are easily fixed by removing the "or".

```yaml
       - or:
          - 2 or more:
            - string: "sites.dat"
            - string: "sites.ini"
            - string: "leapftp"
 ```
From https://github.com/fireeye/capa-rules/blob/master/collection/file-managers/gather-leapftp-information.yml

How about preventing single childs under 'And' or 'Or' ? Should be a quick check in lint.py like: 
```py
if ( statement.name == 'Or' or statement.name == 'And' ) and len( statement.children ) == 1:
    print("Pls remove the useless statement in line ...
```
