### ISSUE TITLE
add coverage for registry manipulation via WMI StdRegProv

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa-rules#470]
> The StdRegProv class contains methods that manipulate system registry keys and values. StdRegProv is preinstalled in the WMI namespaces root\default and root\cimv2.

https://docs.microsoft.com/en-us/previous-versions/windows/desktop/regprov/stdregprov

**Comment by mike-hunhoff** [comment]
based on this: `hxxps://microsoft.public.win32.programmer.wmi.narkive[.]com/e5KHEMoC/using-stdregprov-setdwordvalue-in-c`

`GetObject` must be used to get a referenced to the class, in this case `StdRegProv`, and `GetMethod` must be used to get a reference to the method e.g. `SetStringValue`.

so we could write a rule for `registry manipulation via StdRegProv` containing something like the following:

```yml
- and:
  - string: "StdRegProv"
  - or:
    - string: "SetStringValue"
    - string: "CreateKey"
    - string: "DeleteKey"
    - string: "SetDwordValue"
    - string: "DeleteValue"
```
